[Running] python -u "/home/aquitard/Projects/blog-website-master/sitebuilder.py"
 * Serving Flask app "sitebuilder" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 122-908-539
127.0.0.1 - - [15/Nov/2019 20:50:05] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:50:06] "GET /static/css/style.css HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:50:06] "GET /static/css/button.css HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:50:06] "GET /static/css/popup.css HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:50:06] "GET /static/js/button.js HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:50:06] "GET /static/css/columns.css HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:50:06] "GET /static/pictures/tags.png HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:50:06] "GET /static/pictures/google.png HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:50:06] "GET /static/pictures/favicon.ico HTTP/1.1" 200 -
 * Detected change in '/home/aquitard/Projects/blog-website-master/sitebuilder.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 122-908-539
 * Detected change in '/home/aquitard/Projects/blog-website-master/sitebuilder.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 122-908-539

[Done] exited with code=0 in 221.637 seconds

[Running] python -u "/home/aquitard/Projects/HomePage/tests/test.py"
 * Serving Flask app "test" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 122-908-539
127.0.0.1 - - [15/Nov/2019 20:53:43] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:53:43] "GET /favicon.ico HTTP/1.1" 308 -
127.0.0.1 - - [15/Nov/2019 20:54:24] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aquitard/Projects/HomePage/tests/test.py", line 21, in index
    return render_template('index.html', pages=pages)
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/aquitard/.local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/aquitard/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/aquitard/.local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aquitard/.local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/aquitard/Projects/HomePage/tests/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/aquitard/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/aquitard/Projects/HomePage/tests/templates/index.html", line 14, in root
    
  File "/home/aquitard/Projects/HomePage/tests/templates/base.html", line 14, in root
    {% block content %}
  File "/home/aquitard/Projects/HomePage/tests/templates/index.html", line 26, in block_content
    
  File "/home/aquitard/.local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/aquitard/.local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/aquitard/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _list.html
127.0.0.1 - - [15/Nov/2019 20:54:25] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:54:25] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:54:25] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:54:25] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:54:25] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:54:25] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

[Done] exited with code=0 in 94.452 seconds

[Running] python -u "/home/aquitard/Projects/HomePage/tests/test.py"
 * Serving Flask app "test" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 122-908-539
127.0.0.1 - - [15/Nov/2019 20:56:23] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aquitard/Projects/HomePage/tests/test.py", line 21, in index
    return render_template('index.html', pages=pages)
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/aquitard/.local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/aquitard/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/aquitard/.local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aquitard/.local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/aquitard/Projects/HomePage/tests/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/aquitard/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/aquitard/Projects/HomePage/tests/templates/index.html", line 14, in root
    
  File "/home/aquitard/Projects/HomePage/tests/templates/base.html", line 17, in root
    <link rel="stylesheet" type="text/css" href="/static/css/style.css">
  File "/usr/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/usr/lib/python3.7/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'projects'. Did you mean 'page' instead?
127.0.0.1 - - [15/Nov/2019 20:56:23] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:56:23] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:56:23] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:56:23] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:56:24] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:58:26] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aquitard/Projects/HomePage/tests/test.py", line 21, in index
    return render_template('index.html', pages=pages)
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/aquitard/.local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/aquitard/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/aquitard/.local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aquitard/.local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/aquitard/Projects/HomePage/tests/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/aquitard/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/aquitard/Projects/HomePage/tests/templates/index.html", line 14, in root
    
  File "/home/aquitard/Projects/HomePage/tests/templates/base.html", line 18, in root
    <link rel="stylesheet" type="text/css" href="/static/css/button.css">
  File "/home/aquitard/Projects/HomePage/tests/templates/index.html", line 26, in block_content
    
  File "/home/aquitard/.local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/aquitard/.local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/aquitard/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _list.html
127.0.0.1 - - [15/Nov/2019 20:58:26] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:58:26] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:58:26] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:58:26] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:58:41] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:59:31] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:59:46] "GET /first HTTP/1.1" 308 -
127.0.0.1 - - [15/Nov/2019 20:59:46] "GET /first/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aquitard/Projects/HomePage/tests/test.py", line 34, in page
    page = pages.get_or_404(path)
  File "/usr/lib/python3.7/site-packages/flask_flatpages/flatpages.py", line 103, in get_or_404
    abort(404)
  File "/usr/lib/python3.7/site-packages/werkzeug/exceptions.py", line 772, in abort
    return _aborter(status, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/werkzeug/exceptions.py", line 753, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1815, in handle_user_exception
    return self.handle_http_exception(e)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_http_exception
    return handler(e)
  File "/home/aquitard/Projects/HomePage/tests/test.py", line 40, in page_not_found
    return render_template('404.html'), 404
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/aquitard/.local/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/aquitard/.local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/aquitard/.local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/aquitard/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: 404.html
127.0.0.1 - - [15/Nov/2019 20:59:46] "GET /first/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:59:46] "GET /first/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:59:46] "GET /first/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:59:46] "GET /first/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:59:46] "GET /first/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 20:59:46] "GET /first/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

[Done] exited with code=0 in 237.722 seconds

[Running] python -u "/home/aquitard/Projects/HomePage/tests/test.py"
 * Serving Flask app "test" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 122-908-539
127.0.0.1 - - [15/Nov/2019 21:00:23] "GET /first/ HTTP/1.1" 404 -
127.0.0.1 - - [15/Nov/2019 21:00:42] "GET /first/ HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2019 21:00:42] "GET /static/pictures/MNIST/head-image.png HTTP/1.1" 404 -
127.0.0.1 - - [15/Nov/2019 21:00:42] "GET /static/pictures/MNIST/head-image.png HTTP/1.1" 404 -
127.0.0.1 - - [15/Nov/2019 21:00:44] "GET / HTTP/1.1" 200 -
 * Detected change in '/home/aquitard/Projects/HomePage/tests/test.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "/home/aquitard/Projects/HomePage/tests/test.py", line 6, in <module>
    from flask_flatpages import FlatPages
ModuleNotFoundError: No module named 'flask_flatpages'

[Done] exited with code=1 in 48122.157 seconds

