[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
  File "/home/aquitard/Projects/Weatherpy/test.py", line 4
    "NNE": 22, \ 
                ^
SyntaxError: unexpected character after line continuation character

[Done] exited with code=1 in 0.04 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
  File "/home/aquitard/Projects/Weatherpy/test.py", line 11
    "NE":45, \
"ENE": 74, \
"E": 90, \
"ESE":112, \
"SE": 135, \
"SSE": 157, \
"S" 180:, \ 
        ^
SyntaxError: invalid syntax

[Done] exited with code=1 in 0.036 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
  File "/home/aquitard/Projects/Weatherpy/test.py", line 11
    "S": 180, \ 
               ^
SyntaxError: unexpected character after line continuation character

[Done] exited with code=1 in 0.035 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"

[Done] exited with code=0 in 0.037 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"

[Done] exited with code=0 in 0.036 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"

[Done] exited with code=0 in 0.04 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
0
-22
-23
-29
-16
-22
-23
-22
-23
-22
-23
-22
-23
-22
-23
-22

[Done] exited with code=0 in 0.036 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
0
-22
-23
-22
-23
-22
-23
-22
-23
-22
-23
-22
-23
-22
-23
-22

[Done] exited with code=0 in 0.042 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"

[Done] exited with code=0 in 0.04 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
-180

[Done] exited with code=0 in 0.038 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
-180
-90
180
-180

[Done] exited with code=0 in 0.037 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
-180
-90
180
-180
180
Traceback (most recent call last):
  File "/home/aquitard/Projects/Weatherpy/test.py", line 32, in <module>
    windChange("ENE", "NEE")
  File "/home/aquitard/Projects/Weatherpy/test.py", line 23, in windChange
    x = wind_dir[wd1] - wind_dir[wd2]
KeyError: 'NEE'

[Done] exited with code=1 in 0.037 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
-180
-90
180
-180
180
45

[Done] exited with code=0 in 0.039 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
-180
-90
180
-180
180
Traceback (most recent call last):
  File "/home/aquitard/Projects/Weatherpy/test.py", line 32, in <module>
    windChange("NN", "ENE")
  File "/home/aquitard/Projects/Weatherpy/test.py", line 23, in windChange
    x = wind_dir[wd1] - wind_dir[wd2]
KeyError: 'NN'

[Done] exited with code=1 in 0.036 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
-180
-90
180
-180
180
-45

[Done] exited with code=0 in 0.039 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
180
90
-180
180
-180
45

[Done] exited with code=0 in 0.05 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
  File "/home/aquitard/Projects/Weatherpy/test.py", line 31
    windChange("NW", "SE")s
                          ^
SyntaxError: invalid syntax

[Done] exited with code=1 in 0.036 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
180
90
-180
180
-180
45

[Done] exited with code=0 in 0.035 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
315
-90
180
-180
180
-45

[Done] exited with code=0 in 0.04 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"

[Done] exited with code=0 in 0.035 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
315

[Done] exited with code=0 in 0.032 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
-315

[Done] exited with code=0 in 0.04 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
315
-90
180
-180
180
-45

[Done] exited with code=0 in 0.036 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
-495
-90
180
-180
180
-45

[Done] exited with code=0 in 0.037 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
135
-90
180
-180
180
-45

[Done] exited with code=0 in 0.041 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
-45
-90
180
-180
180
-45

[Done] exited with code=0 in 0.039 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
-45
Traceback (most recent call last):
  File "/home/aquitard/Projects/Weatherpy/test.py", line 36, in <module>
    windChange("NE", "SE")
  File "/home/aquitard/Projects/Weatherpy/test.py", line 25, in windChange
    print(x)
UnboundLocalError: local variable 'x' referenced before assignment

[Done] exited with code=1 in 0.037 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
-45

[Done] exited with code=0 in 0.036 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
-45
-90
180
-180
180
-45

[Done] exited with code=0 in 0.045 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
45
90
180
180
180
45

[Done] exited with code=0 in 0.047 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
  File "/home/aquitard/Projects/Weatherpy/test.py", line 27
    x = wind_dir[wd1] - wind_dir[wd2] - 360)
                                           ^
SyntaxError: unmatched ')'

[Done] exited with code=1 in 0.037 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"

[Done] exited with code=0 in 0.035 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
248

[Done] exited with code=0 in 0.037 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
over 180
248

[Done] exited with code=0 in 0.04 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
over 180
248

[Done] exited with code=0 in 0.038 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
over 180
248

[Done] exited with code=0 in 0.036 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
over 180
248

[Done] exited with code=0 in 0.035 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
over 180
248

[Done] exited with code=0 in 0.037 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
over 180
248

[Done] exited with code=0 in 0.049 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
over 180
248

[Done] exited with code=0 in 0.039 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
over 180
248

[Done] exited with code=0 in 0.042 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
over 180
248

[Done] exited with code=0 in 0.036 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
over 180
248

[Done] exited with code=0 in 0.053 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
over 180
248

[Done] exited with code=0 in 0.035 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
over 180
248

[Done] exited with code=0 in 0.038 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
over 180
Traceback (most recent call last):
  File "/home/aquitard/Projects/Weatherpy/test.py", line 39, in <module>
    print(windChange("NNEE", "W"))
  File "/home/aquitard/Projects/Weatherpy/test.py", line 24, in windChange
    if wind_dir[wd1] - wind_dir[wd2] <= 180:
KeyError: 'NNEE'

[Done] exited with code=1 in 0.034 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
over 180
248

[Done] exited with code=0 in 0.038 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
over 180
1

[Done] exited with code=0 in 0.042 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
over 180
over 180
1540

[Done] exited with code=0 in 0.039 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
over 180
over 180
540

[Done] exited with code=0 in 0.035 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
over 180
over 180
0

[Done] exited with code=0 in 0.042 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
over 180
over 180
248

[Done] exited with code=0 in 0.042 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
over 180
over 180
608

[Done] exited with code=0 in 0.039 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
over 180
over 180
112

[Done] exited with code=0 in 0.041 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
over 180
675
1
1
1
1
over 180
112
112

[Done] exited with code=0 in 0.036 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
over 180
675
90
180
180
180
over 180
112
112

[Done] exited with code=0 in 0.038 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
over 180
315
90
180
180
180
over 180
248
248

[Done] exited with code=0 in 0.038 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
over 180
45
90
180
180
180
over 180
608
608

[Done] exited with code=0 in 0.037 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
over 180
45
90
180
180
180
over 180
112
112

[Done] exited with code=0 in 0.035 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
45
90
180
180
180
112
112

[Done] exited with code=0 in 0.042 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
45
90
180
180
180
112

[Done] exited with code=0 in 0.038 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
-45
90
180
180
180
-112

[Done] exited with code=0 in 0.037 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
45
90
180
180
180
112

[Done] exited with code=0 in 0.036 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"
Traceback (most recent call last):
  File "/home/aquitard/Projects/Weatherpy/test.py", line 3, in <module>
    from weather_au import api, observations
  File "/usr/lib/python3.8/site-packages/weather_au/__init__.py", line 3, in <module>
    import bs4 # uses lxml
ModuleNotFoundError: No module named 'bs4'

[Done] exited with code=1 in 0.04 seconds

[Running] python -u "/home/aquitard/Projects/Weatherpy/test.py"

Observations (temp): 16.3
45
90
180
180
180
112

[Done] exited with code=0 in 2.453 seconds

